### PR TITLE
[ADD] xifetch and xifetch-rs

### PR DESCRIPTION
**Pull request by aelloc**
I did not copy the whole project to this repo. I just used submodule, it may have problems.

~THanks!!!

### CODE REVIEW

**Comment by SaDi-BRo** [comment]
I think there are `.git` directories which you added. Could you delete them and also `.gitmodule`. Rename the directories with the technology's name. Such as `python` or `rust`

**Comment by aelloc** [comment]
i think i can't, because it's how submodules work

**Comment by SaDi-BRo** [comment]
If I try to enter xifetch directory that redirects me to https://github.com/reilinux/xifetch. Please make sure that everything is right

**Comment by aelloc** [comment]
that is why i used submodules

**Comment by SaDi-BRo** [comment]
You shouldn't make submodules. Just copy your own neofetch project into this repo. and push it. See no one did like this

**Comment by SaDi-BRo** [comment]
Will you commit?

**Comment by aelloc** [comment]
~OKAY!!!

**Pull request closed without merging**
